class RandomGenerator{
    constructor(minimum = 1, maximum = 10){
        this.minimum = minimum;
        this.maximum = maximum;
        this.randomNumber = null;


        //takes in the minimum and maximum values
        //if they are not defined, it sets the minimum to 1, and the max to 10
        //makes storage for the random number
    }
    generate(){

        this.randomNumber = Math.floor(Math.random() * (this.maximum - this.minimum + 1)) + this.minimum;
        //make a random value between the minimum and maximum values
        //and store the number into the storage from the constructor
    }
    getRange(){

        const minAndMax = {
            min : this.minimum,
            max : this.maximum

        }
        return minAndMax;
        //return an object with min and max, min being the minimum value for the generator, max being the maximum value
        //returns a basic object literal
    }
    getNum(){
        this.generate();
        return this.randomNumber;
        //return the random number that was generated by generate()
    }
}